name: SimpleBackup
main: com.exolius.simplebackup.SimpleBackup
version: ${project.version}
softdepend: [Multiverse-Core]

commands:
   sbackup:
      description: Run map backup
      usage: /sbackup

permissions:
   simplebackup.use:
      description: Run map backup
      default: op
